source = /usr/local/share/narchos/default/hypr/bindings/media.conf
source = /usr/local/share/narchos/default/hypr/bindings/tiling.conf
source = /usr/local/share/narchos/default/hypr/bindings/utilities.conf
