# App-specific tweaks
source = $NARCHOS_PATH/default/hypr/ui/apps/browser.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/copyq.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/hyprshot.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/pip.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/qemu.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/retroarch.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/steam.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/system.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/terminals.conf
source = $NARCHOS_PATH/default/hypr/ui/apps/walker.conf
