# App-specific tweaks
source = /usr/local/share/narchos/default/hypr/ui/apps/browser.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/copyq.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/hyprshot.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/pip.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/qemu.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/retroarch.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/steam.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/system.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/terminals.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/walker.conf
source = /usr/local/share/narchos/default/hypr/ui/apps/webcam-overlay.conf
