# All the default narchos aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/narchos/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
alias py='python'
