# https://wiki.hypr.land/Configuring/Variables/#general
general {
    border_size = 2
    gaps_in = 2
    gaps_out = 2

    # https://wiki.hypr.land/Configuring/Variables/#snap
    snap {
        enabled = true
        window_gap = 30
        monitor_gap = 30
        border_overlap = true
        respect_gaps = true
    }
}
