# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use narchos defaults (but don't edit these directly!)
$NARCHOS_PATH = /usr/local/share/narchos
source = $NARCHOS_PATH/default/hypr/autostart.conf
source = $NARCHOS_PATH/default/hypr/bindings.conf
source = $NARCHOS_PATH/default/hypr/envs.conf
source = $NARCHOS_PATH/default/hypr/input.conf
source = $NARCHOS_PATH/default/hypr/ui.conf
source = ~/.config/narchos/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/ui.conf
