source = "$NARCHOS_PATH/default/hypr/ui/layout/all.conf"
source = "$NARCHOS_PATH/default/hypr/ui/animations.conf"
source = "$NARCHOS_PATH/default/hypr/ui/decoration.conf"
source = "$NARCHOS_PATH/default/hypr/ui/general.conf"
source = "$NARCHOS_PATH/default/hypr/ui/misc.conf"
source = "$NARCHOS_PATH/default/hypr/ui/windowrules.conf"
