source = /usr/local/share/narchos/default/hypr/ui/layout/all.conf
source = /usr/local/share/narchos/default/hypr/ui/animations.conf
source = /usr/local/share/narchos/default/hypr/ui/decoration.conf
source = /usr/local/share/narchos/default/hypr/ui/general.conf
source = /usr/local/share/narchos/default/hypr/ui/misc.conf
source = /usr/local/share/narchos/default/hypr/ui/windowrules.conf
