group {
    groupbar {
        gradients = true
        height = 4
        indicator_height = 0
        indicator_gap = 2
        render_titles = false
        stacked = false
        gradient_rounding = 4
        gradient_rounding_power = 3
        gradient_round_only_edges = false
        col.active = rgba(164,126,180,1)
        col.inactive = rgba(30,30,30,1)
        col.locked_active = rgba(164,126,180,1)
        col.locked_inactive = rgba(30,30,30,1)
        gaps_in = 0
        gaps_out = -2
        keep_upper_gap = false
    }
}
